// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * TypeCharacter types the given character at the current cursor position
 */
export function TypeCharacter(char: string): $CancellablePromise<void> {
    return $Call.ByID(1111630857, char);
}
